Week4/Day16/Lesson_Rails/timetracking/config/routes.rb
Rails.application.routes.draw do
  get "/", to: "site#home"
  get "/about", to: "site#about"
  get "/contact", to: "site#contact"
  get "/say_name/:name", to: "site#say_name"
  get "/add_form", to: "calculator#add_form"
  post "/calculator", to: "calculator#process_addition"
  resources :projects do
    resources :time_entries  # <= Nested resources/routes
  end
  # resources :projects, only: [:index, :show, :new, :create] do
  #   resources :time_entries, except: [:show]  # <= Nested resources/routes
  # end
end

Week4/Day16/Lesson_Rails/timetracking/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Week4/Day16/Lesson_Rails/timetracking/app/models/project.rb
class Project < ApplicationRecord
	has_many :time_entries
	validates :name, presence: true, uniqueness: true
	validates :descript, presence: true
end

Week4/Day16/Lesson_Rails/timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord
	belongs_to :project
	validates :date, presence: true
	validates :hours, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :minutes, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :comment, presence: true
end

Week4/Day16/Lesson_Rails/timetracking/app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
	def add_form
		render 'add_form'
	end
	def process_addition
		@number1 = params[:number1].to_i
		@number2 = params[:number2].to_i
		@result = @number1 + @number2
		render "results"
	end
end

Week4/Day16/Lesson_Rails/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.order(created_at: :desc) .limit(10) #.where.not(descript: nil) <-- Removes No. 7 completely. No bueno?
		render :index
	end
	def show
		@my_project = Project.find(params[:id])
		render :show
	end
	def new
		@my_project = Project.new
		render :new
	end
	def create
		@my_project = Project.new(entry_params)
		@my_project.save
		redirect_to project_path(@my_project)
	end
	def edit
		@my_project = Project.find(params[:id])
		render :edit
	end
	def update
		@my_project = Project.find(params[:id])
		if @my_project.update(entry_params)
			redirect_to project_path(@my_project)
		else
			render :edit
		end
	end
	def destroy
		@my_project = Project.find(params[:id])
		@my_project.destroy()
		redirect_to project_path(@my_project)
	end
	private
	def entry_params
		params.require(:project).permit(:name, :descript)
	end
end

Week4/Day16/Lesson_Rails/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		render 'home' # name of view template
	end
	def about
		render 'about'
	end
	def contact
		render 'contact'
	end
	def say_name
		@name = params[:name]
		render 'say_name'
	end
end

Week4/Day16/Lesson_Rails/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def index
		@my_project = Project.find(params[:project_id])
		@my_entries = @my_project.time_entries
		render :index
	end
	def new
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.new
		render :new
	end
	def create
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.new(entry_params)
		if @my_entry.save
			redirect_to project_time_entries_path(@my_project)		# "/projects/#{@my_project.id}/time_entries"
		else
			render :new
		end
	end
	def edit
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.find(params[:id])
		render :edit
	end
	def update
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.find_by(id: params[:id])

		if @my_entry.update(entry_params)
			redirect_to project_time_entries_path(@my_project)
		else
			render :edit
		end 
	end
	def destroy
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.find_by(id: params[:id])
		@my_entry.destroy()
		redirect_to project_time_entries_path(@my_project)
	end
	private
	def entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date, :comment)
	end
end

Week4/Day16/Lesson_Rails/timetracking/app/helpers/application_helper.rb
module ApplicationHelper
	
end

Week4/Day16/Lesson_Rails/timetracking/app/helpers/calculator_helper.rb
module CalculatorHelper
end

Week4/Day16/Lesson_Rails/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

Week4/Day16/Lesson_Rails/timetracking/app/helpers/site_helper.rb
module SiteHelper
	
end

Week4/Day16/Lesson_Rails/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

Week4/Day16/Lesson_Rails/timetracking/app/views/inc/_navigation.html.erb
<nav>
	<ul>
		<li><%= link_to_unless_current "Home", "/" %></li>
		<li><%= link_to_unless_current "About", about_path %></li>
		<li><%= link_to_unless_current "Contact", contact_path %></li>
		<li><%= link_to_unless_current "Calculator", add_form_path %></li>
		<li><%= link_to_unless_current "Projects", projects_path %>
			<!-- <ul class="dropdown">
				<li>< %= link_to_unless_current "Add Task", "/projects/new" %>
			</ul> -->
		</li>
	</ul>
</nav>

Week4/Day16/Lesson_Rails/timetracking/app/views/projects/_form.html.erb
<%= form_for @my_project do |form| %>
	<fieldset>
		<%= form.label :name %>
		<%= form.text_field :name %>
	</fieldset>
	<fieldset>
		<%= form.label :descript %>
		<%= form.text_area :descript %>
	</fieldset>
	<%= form.button %>
	<%= link_to 'Cancel', projects_path %>
<% end %>

Week4/Day16/Lesson_Rails/timetracking/app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render "form" %>
<small><%= link_to "Back to Tasks", projects_path %></small>

Week4/Day16/Lesson_Rails/timetracking/app/views/projects/index.html.erb
<h2>Projects Home</h2>
<br>
<table id="projects">
	<tbody>
		<% @projects.each do |project| %>
			<tr>
				<td><%= link_to project.name, project_path(project.id) %></td>
				<td>
					<% if project.descript.present? %>
						<%= project.descript %>
					<%else %>
						&nbsp;
					<% end %>
				</td>
				<td>
					<%= link_to "Edit", edit_project_path(project.id) %>
					<br><%= link_to "Delete", project_path(project.id), method: "delete", data: { confirm: "Are you sure?" } %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<div id="cta"><%= link_to "Add New Task", new_project_path %></div>

Week4/Day16/Lesson_Rails/timetracking/app/views/projects/new.html.erb
<h2>Create a New Task</h2>
<%= render "form" %>
<small><%= link_to "Back to Tasks", projects_path %></small>

Week4/Day16/Lesson_Rails/timetracking/app/views/projects/show.html.erb
<h2>Task: <strong><%= @my_project.name %></strong></h2>
<p><em><%= @my_project.descript %></em></p>

<h3>Project Details</h3>
<table id="task">
	<tbody>
		<tr>
			<td width="30%">ID:</td>
			<td><strong><%= @my_project.id %></strong></td>
		</tr>
		<tr>
			<td>Created:</td>
			<td><strong><%= @my_project.created_at %></strong></td>
		</tr>
		<tr>
			<td>Updated:</td>
			<td><strong><%= @my_project.updated_at %></strong></td>
		</tr>
	</tbody>
</table>

<div id="cta"><%= link_to "View Time Entries", project_time_entries_path(@my_project) %></div>
<br>
<small><%= link_to "View All Tasks", projects_path %><%= link_to "Add New Task", new_project_path %></small>