Week4/Day16/EX_PathHelpers/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'visitors#home', as: :home
  get '/company/about' => 'visitors#about', as: :about
  get '/blog' => 'visitors#blog'
  get '/contact' => 'visitors#contact'
end

Week4/Day16/EX_PathHelpers/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def about
	end

	def blog
	end

	def contact
	end

	def home 
	end
end

Week4/Day16/EX_PathHelpers/app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </div>
</footer>

Week4/Day16/EX_PathHelpers/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

Week4/Day16/EX_PathHelpers/app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <%#= link_to 'Business Casual', root_path, class: 'navbar-brand' %>
            <a href="/" class="navbar-brand">Business Casual</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <%= render 'layouts/navigation_links' %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

Week4/Day16/EX_PathHelpers/app/views/layouts/_navigation_links.html.erb
<li><%= link_to_unless_current 'Home', home_path %></li>
<li><%= link_to_unless_current 'About', about_path %></li>
<li><%= link_to_unless_current 'Blog', blog_path %></li>
<li><%= link_to_unless_current 'Contact', contact_path %></li>

Week4/Day16/EX_PathHelpers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body>
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>